name: Build MicroPython ADF Firmware

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget flex bison gperf python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util

    - name: Setup ESP-IDF
      uses: espressif/esp-idf-action@v2
      with:
        version: 'release/v5.1'

    - name: Export ESP-IDF environment
      run: . $HOME/.espressif/esp-idf/export.sh

    - name: Configure project
      run: idf.py set-target esp32  # change target if needed

    - name: Build firmware
      run: idf.py build

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: build/firmware.bin
