name: Build Slim MicroPython ADF Firmware

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ESP-IDF
        uses: espressif/esp-idf-action@v3
        with:
          version: v5.3.2  # Change to the ESP-IDF version your ADF requires

      - name: Install minimal Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyserial

      - name: Build firmware
        run: |
          idf.py set-target esp32
          idf.py build

      - name: Upload firmware.bin artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.bin
