name: Build ESP32 MicroPython ADF Firmware

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_firmware:
    name: Build Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4
          target: esp32

      - name: Export ESP-IDF environment
        run: . $HOME/.espressif/esp-idf/export.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Build Firmware
        run: idf.py build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.bin
